<?php

$err='';

if (!empty($data->status))
{
	$err.='<div class="section__errors">';
	
	if($data->status == "access_granted")
	{
		$err.='<p class="section__errors_green">'.$data->status.'</p>';
	}
	else
	{
		$err.='<p class="section__errors_green">'.$data->status.'</p>';
	}	 
	$err.='</div>';
}

if (!empty($err))
{
	echo $err;
}
else
{
?>
<section class="section">

	<h2 class="h2 py-2 text-center">Редактирование пользователей</h2>

<?php if (!empty($data->all)){ ?>

	<div class="container">
		<a href="/edituser/edit/" class="btn btn-primary">Добавить пользователя</a>
	</div>

		<div class="section__table">

		<div class="table__row">
			<div class="table__btn">Действие</div>
			<div class="table__btn"></div>
			<div class="table__id">ID</div>
			<div class="table__login">Логин</div>
			<div class="table__balance">Баланс</div>
			<div class="table__active">Актив.</div>
			<div class="table__is_admin">Админ</div>
			<div class="table__ip">IP посл. входа</div>
			<div class="table__name">Ник</div>
			<div class="table__datetime">Дата посл. входа</div>
		</div>

<?php foreach ($data->all as $key=>$val){ ?>
			<div class="table__row">
		<?php foreach ($val as $k=>$v)
		{
				if($k == 'password')
				{
					continue;
				}

				if ($k == 'is_admin'or $k == 'active')
				{
					echo '<div class="table__'.$k.'">'.(($v == 0) ? 'нет' : 'да').'</div>';
					continue;
				}

				if ($k == 'id')
				{ ?>
					<div class="table__btn"><a href="/edituser/edit/<?=$v; ?>" class="link-danger">Изменить</a></div>

					<form class="table__btn" action="/edituser/delete" method="POST">
						<button class="btn btn-danger btn-sm" name="del" value="<?=$v; ?>">Удалить</button>
					</form>
				<?php }

				if ($k == 'datetime')
				{ 
					echo '<div class="table__datetime">'.date('d.m.Y H:i:s', $v).'</div>';
					continue;
				}
				echo '<div class="table__'.$k.'">'.$v.'</div>';
		} ?>
			</div>

		<?php } ?>

		</div>

<?php
}
else
{
?>
	<!-- форма добавления/редактирования пользователя -->
	<div class="container">
		<div class="row justify-content-center">
			<div class="col-md-4">

			<form action="/edituser/edit/<?=(!empty($data->one->id) ? $data->one->id : ''); ?>" method="POST">
			<!-- csrf -->
			<input type="hidden" name="tkn" class="form__input" id="tkn" value="<?=$_SESSION['tkn']; ?>">
			<legend>Введите данные пользователя</legend>

			<div class="form-floating mb-3">
				<label for="login">Логин</label>
				<input type="text" class="form-control" name="login" id="login" value="<?=(!empty($data->one->login) ? $data->one->login : ''); ?>">
			</div>

			<div class="form-floating mb-3">
				<label for="password">Пароль</label>
				<input type="password" class="form-control" name="password" id="password" value="">
			</div>

			<div class="form-floating mb-3">
				<label for="balance">Баланс лицевого счета</label>
				<input type="number" step="0.01" min="0" placeholder="0,00" class="form-control" name="balance" id="balance" value="<?=(!empty($data->one->balance) ? $data->one->balance : 0); ?>">
			</div>

			<div class="form-floating mb-3">
				<label for="name">Ник</label>
				<input type="text" class="form-control" name="name" id="name" value="<?=(!empty($data->one->name) ? $data->one->name : ''); ?>">
			</div>

			<div class="form-floating mb-3">
				<label for="active">Аккаунт активирован</label>
				<select class="form-control" name="active" id="active">
				<option value="<?=(!empty($data->one->active)?$data->one->active : 0); ?>"><?=(!empty($data->one->active) ? 'Да' : 'Нет'); ?></option>
				<option value="0">Нет</option>
				<option value="1">Да</option>
				</select>
			</div>

			<div class="form-floating mb-3">
				<label for="is_admin">Назначить администратором</label>
				<select class="form-control" name="is_admin" id="is_admin">
				<option value="<?=(!empty($data->one->is_admin) ? $data->one->is_admin : 0); ?>"><?=(!empty($data->one->is_admin) ? 'Да' : 'Нет'); ?></option>
				<option value="0">Нет</option>
				<option value="1">Да</option>
				</select>
			</div>

			<div class="col-sm form-floating mt-1">    
            	<input type="submit" name="btn" class="btn btn-success" value="Сохранить">
				<a href="/edituser/" class="btn btn-success">Назад</a>
        	</div>
			
			</form>
			</div>
		</div>
	</div>
	
	<div><?=$err; ?></div>

<?php } ?>
</section>
<?php } ?>