<!DOCTYPE html>
<html lang="ru">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>SF-Final</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha1/css/bootstrap.min.css" integrity="sha384-r4NyP46KrjDleawBgD5tp8Y7UzmLA05oM1iAEQ17CSuDqnUK2+k9luXQOfXJCJ4I" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="/public/css/flash.css" />
    <link rel="stylesheet" type="text/css" href="/public/css/table.css" />
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha1/js/bootstrap.min.js" integrity="sha384-oesi62hOLfzrys4LxRF63OJCXdXDipiYWBnvTl9Y9/TRlw5xlKIEHpNyvvDShgf/" crossorigin="anonymous"></script>
</head>

<body>

    <div class="container bg-light">
        <div class="row">

            <header class="header">
                <?php include 'layouts/header.phtml'; ?>
            </header>

                <div class="container" style="min-height: 1440px;">
                    <main class="main">
                    <?php include VIEW . DIRECTORY_SEPARATOR . $content_view; ?>
                    </main>
                </div>

            <footer class="footer fixed-bottom">
                <?php include 'layouts/footer.phtml'; ?>
            </footer>

        </div>
    </div>

</body>

</html>