<?php
use App\models\Model_User;
?>
<div class="container">
    <div class="row">

        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container-fluid">
                <a class="navbar-brand" href="/">SF-Final. AdTech</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Переключатель навигации">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav ml-auto mb-2 mb-lg-0">

                        <li class="nav-item">
                            <a class="nav-link" aria-current="page" href="/">Главная</a>
                        </li>

                        <?php if (isset($_SESSION['role']) and $_SESSION['role'] == 'admin') : ?>                        
                        <li class="nav-item">
                            <a class="nav-link" href="/budget/">Статистика и бюджет</a>
                        </li>
                        
                        <li class="nav-item">
                            <a class="nav-link" href="/edituser/">Пользователи</a>
                        </li>                        
                        <?php endif;?>
                        
                        <?php if (Model_User::checkAuth()) : ?>
                        <li class="nav-item">                            
                            <a class="nav-link" href="/admin/">Офферы</a>
                        </li>

                        <li class="nav-item">                            
                            <a class="nav-link" href="/admin/logout"><?=strtoupper($_SESSION['runame'])?> Выход</a>
                        </li>


                        <?php elseif (!Model_User::checkAuth()) : ?>
                        <li class="nav-item">
                            <a class="nav-link" aria-current="page" href="register">Регистрация</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link" href="login">Вход</a>
                        </li>
                        <?php endif; ?>
                        
                    </ul>
                </div>
            </div>
        </nav>
    </div>
</div>